"""
state.py — Pydantic state schema for v6 long-term memory RAG.

Extends v5.5 AgentState with four memory fields:
  - session_id         : thread identifier, generated once per session
  - session_history    : list of MemoryEntry objects accumulated this session
  - retrieved_memories : top-k past episodes injected as context for this query
  - memory_injected    : flag set True once retrieved_memories is written to state

MemoryEntry is a lightweight record of one completed query-answer cycle,
persisted to the memory_episodes PostgreSQL table after each successful run.
"""

from __future__ import annotations

from datetime import datetime
from pydantic import BaseModel, Field


# ---------------------------------------------------------------------------
# Memory episode record
# ---------------------------------------------------------------------------

class MemoryEntry(BaseModel):
    session_id: str
    query: str
    answer: str
    score: float
    store_used: str
    created_at: datetime = Field(default_factory=datetime.utcnow)


# ---------------------------------------------------------------------------
# Agent state — v5.5 fields + memory fields
# ---------------------------------------------------------------------------

class AgentState(BaseModel):
    # Core query
    query: str
    query_type: str = ""

    # Attempt management
    attempt: int = 0
    max_attempts: int = 3

    # Retrieval context fields — accumulated across retries
    sql_context: str = ""
    vector_context: str = ""
    graph_context: str = ""
    accumulated_context: str = ""   # grows with each retry
    context: str = ""               # current attempt's assembled context

    # Answer fields
    answer: str = ""
    previous_answer: str = ""       # answer from attempt before current

    # Judge fields
    verdict: str = ""               # "good" | "insufficient"
    evaluation: str = ""            # judge's description of what is missing
    score: float = 0.0
    score_trend: list[float] = Field(default_factory=list)
    min_score_threshold: float = 0.3
    judge_parse_error: bool = False

    # Cross-store fallback (v5.5)
    fallback_store: str = ""        # "postgresql" | "chromadb" | "networkx" | ""

    # Long-term memory (v6) -----------------------------------------------
    session_id: str = ""            # thread_id; generated by agent if empty
    session_history: list[MemoryEntry] = Field(default_factory=list)
    retrieved_memories: list[MemoryEntry] = Field(default_factory=list)
    memory_injected: bool = False   # True once memory_retrieval_node has run
    query_embedding: list[float] = Field(default_factory=list)
